import type { CritterDef } from '../sim/types';

/**
 * The Infestation — Phase 1 bestiary (Kitchen campaign).
 * desc fields are Critterdex entries, written in the kid's field-journal voice.
 */
export const CRITTER_DEFS: Record<string, CritterDef> = {
  'ant-worker': {
    id: 'ant-worker', name: 'Worker Ant', tier: 1,
    hp: 14, speed: 2.2, size: 0.22, bounty: 4, bites: 1,
    resist: null, weak: 'spray',
    crumbHunger: 12, evolveTo: 'ant-soldier',
    desc: 'The basic unit of crime. One is nothing. One is never one. DO NOT leave crumbs out, they get IDEAS and also SHOULDERS.',
  },
  'ant-soldier': {
    id: 'ant-soldier', name: 'Soldier Ant', tier: 2,
    hp: 34, speed: 2.0, size: 0.3, bounty: 7, bites: 1,
    resist: 'gas', weak: 'spray', armor: 1,
    desc: 'A worker ant that ate its vegetables (our crumbs). Has a helmet now?? Where did it get a helmet.',
  },
  'ant-bullet': {
    id: 'ant-bullet', name: 'Bullet Ant', tier: 2,
    hp: 10, speed: 4.2, size: 0.2, bounty: 5, bites: 1,
    resist: null, weak: 'cold',
    desc: 'NyoooOOOOM. Blink and it\'s in the pantry. Cold makes it grumpy and slow, like dad before coffee.',
  },
  'fly-house': {
    id: 'fly-house', name: 'Housefly', tier: 1,
    hp: 16, speed: 2.8, size: 0.28, bounty: 6, bites: 1,
    resist: 'spray', weak: 'swat', flying: true,
    traits: ['dodgeFirst'],
    desc: 'Dodges the first swing EVERY TIME like it\'s showing off. The second swing is personal.',
  },
  'fly-fruit': {
    id: 'fly-fruit', name: 'Fruit Fly', tier: 1,
    hp: 3, speed: 3.2, size: 0.15, bounty: 1, bites: 1,
    resist: null, weak: 'gas', flying: true,
    desc: 'Individually: nothing. Collectively: a weather system with opinions about bananas.',
  },
  'roach': {
    id: 'roach', name: 'Cockroach', tier: 3,
    hp: 60, speed: 1.7, size: 0.42, bounty: 12, bites: 1,
    resist: 'swat', weak: 'gas', armor: 1,
    traits: ['playDead'],
    desc: 'Plays dead and you WILL fall for it. Grandpa says they\'ll outlive the sun. The sun should watch its back.',
  },
  'mouse-thief': {
    id: 'mouse-thief', name: 'Mouse Thief', tier: 3,
    hp: 90, speed: 3.6, size: 0.55, bounty: 20, bites: 0,
    resist: 'cold', weak: 'zap',
    traits: ['thief'], chewDps: 12,
    desc: 'Does NOT nibble. Takes the WHOLE SLICE and runs like it has a getaway car. GET IT BEFORE THE EXIT!!',
  },
  'slug': {
    id: 'slug', name: 'Slug', tier: 2,
    hp: 50, speed: 0.8, size: 0.38, bounty: 10, bites: 1,
    resist: 'spray', weak: 'heat',
    desc: 'Slow. SO slow. But it never stops. It\'s probably behind you right now. (Check tomorrow.)',
  },
  'snail': {
    id: 'snail', name: 'Snail', tier: 3,
    hp: 80, speed: 0.6, size: 0.4, bounty: 14, bites: 1,
    resist: 'swat', weak: 'heat', armor: 4,
    desc: 'A slug that found ARMOR. The shell counts as a house, which makes this a home invasion BY a home.',
  },
  'moth': {
    id: 'moth', name: 'Moth', tier: 2,
    hp: 22, speed: 2.4, size: 0.35, bounty: 8, bites: 1,
    resist: 'cold', weak: 'heat', flying: true,
    desc: 'Like a butterfly that gave up. Obsessed with the lamp. The lamp does not feel the same way.',
  },
  'dust-bunny': {
    id: 'dust-bunny', name: 'Dust Bunny', tier: 2,
    hp: 26, speed: 1.4, size: 0.45, bounty: 6, bites: 1,
    resist: 'swat', weak: 'spray',
    splitInto: { def: 'dust-bunnette', count: 2 },
    desc: 'From the Under-Couch Dimension. Hit it and it becomes TWO smaller problems. Math is against us.',
  },
  'dust-bunnette': {
    id: 'dust-bunnette', name: 'Dust Bunnette', tier: 1,
    hp: 8, speed: 1.8, size: 0.25, bounty: 2, bites: 1,
    resist: null, weak: 'spray',
    desc: 'A dust bunny\'s revenge. Smaller, faster, somehow angrier.',
  },
  'stinkbug': {
    id: 'stinkbug', name: 'Stink Bug', tier: 3,
    hp: 45, speed: 1.5, size: 0.4, bounty: 12, bites: 1,
    resist: 'gas', weak: 'swat',
    traits: ['deathGas'],
    desc: 'A walking dare. Pop it near your towers and they ALL take a smell break. Pop it far away. FAR. AWAY.',
  },
  'crumb-king': {
    id: 'crumb-king', name: 'The Crumb King', tier: 5,
    hp: 1400, speed: 0.55, size: 1.1, bounty: 150, bites: 3,
    resist: 'spray', weak: null, boss: true, chewDps: 30,
    traits: ['crumbShed', 'crumbHeal'],
    desc: 'A royal wad of every crumb ever lost behind the toaster. Drops crumbs. EATS crumbs. HEALS with crumbs. SWEEP DURING THE FIGHT or he never ever falls. His first words were "let them eat cake — let ME eat cake."',
  },
  'ant-fire': {
    id: 'ant-fire', name: 'Fire Ant', tier: 2,
    hp: 28, speed: 3.0, size: 0.24, bounty: 7, bites: 1,
    resist: 'heat', weak: 'cold',
    desc: 'Red and zoomy and too spicy for its pants. I drew flames on the page but Mom said stop labeling real ants "touch later."',
  },
  'ant-carpenter': {
    id: 'ant-carpenter', name: 'Carpenter Ant', tier: 2,
    hp: 42, speed: 1.9, size: 0.32, bounty: 11, bites: 1,
    resist: 'swat', weak: 'gas', chewDps: 14,
    desc: 'Carries tiny wood plans. Still wants cake, but if a wall is rude it becomes sawdust with legs.',
  },
  'maggot': {
    id: 'maggot', name: 'Maggot', tier: 1,
    hp: 18, speed: 0.75, size: 0.2, bounty: 5, bites: 1,
    resist: 'cold', weak: 'heat',
    traits: ['timedEvolve'], evolveAfter: 15, evolveTo: 'fly-house',
    desc: 'A rice grain that learned bad news. If it lives too long it graduates into a fly, which is NOT an improvement.',
  },
  'roach-winged': {
    id: 'roach-winged', name: 'Winged Roach', tier: 3,
    hp: 85, speed: 1.85, size: 0.44, bounty: 22, bites: 1,
    resist: 'swat', weak: 'light', armor: 1,
    traits: ['lateFlier'],
    desc: 'Walks normal until the cake is close, then remembers it has a villain cape. I hate when bugs have plot twists.',
  },
  'roach-nuclear': {
    id: 'roach-nuclear', name: 'Nuclear Roach', tier: 4,
    hp: 210, speed: 1.35, size: 0.55, bounty: 53, bites: 1,
    resist: 'zap', weak: 'gas', armor: 3,
    traits: ['playDead'], playDeadTimes: 1,
    desc: 'Glows like a night-light that pays taxes. Plays dead, then gets up like the floor was just a suggestion.',
  },
  'possum-jr': {
    id: 'possum-jr', name: 'Possum Jr.', tier: 3,
    hp: 120, speed: 1.45, size: 0.62, bounty: 30, bites: 1,
    resist: 'cold', weak: 'sonic',
    traits: ['playDead'], playDeadTimes: 2,
    desc: 'Falls over dramaticly. Then again. If acting was illegal this baby would be in jail and also still eating cake.',
  },
  'bedbug': {
    id: 'bedbug', name: 'Bedbug', tier: 3,
    hp: 55, speed: 2.1, size: 0.25, bounty: 14, bites: 1,
    resist: 'swat', weak: 'light',
    traits: ['stealth'],
    desc: 'A walking freckle with secrets. You need lamp light or it becomes invisible, which is cheating in my own house.',
  },
  'cricket-bard': {
    id: 'cricket-bard', name: 'Cricket Bard', tier: 3,
    hp: 70, speed: 2.4, size: 0.34, bounty: 18, bites: 1,
    resist: 'sonic', weak: 'swat',
    traits: ['speedAura'],
    desc: 'Sings CHIRP CHIRP and everybody gets faster. Worst band ever. No merch table, only panic.',
  },
  'centipede': {
    id: 'centipede', name: 'Centipede', tier: 4,
    hp: 240, speed: 1.25, size: 0.78, bounty: 60, bites: 1,
    resist: 'spray', weak: 'cold', armor: 2,
    splitInto: { def: 'centipede-half', count: 2 },
    desc: 'Too many shoes and none of them tied. If you break it, it becomes TWO homework problems with legs.',
  },
  'centipede-half': {
    id: 'centipede-half', name: 'Centipede Half', tier: 3,
    hp: 95, speed: 1.75, size: 0.48, bounty: 24, bites: 1,
    resist: 'gas', weak: 'swat', armor: 1,
    splitInto: { def: 'centipede-bit', count: 2 },
    desc: 'Half a nope, moving faster because it is late for being whole. Still has too many knees.',
  },
  'centipede-bit': {
    id: 'centipede-bit', name: 'Centipede Bit', tier: 2,
    hp: 34, speed: 2.6, size: 0.24, bounty: 9, bites: 1,
    resist: null, weak: 'spray',
    desc: 'A loose wiggle. Small enuff to miss and fast enuff to make you say words Dad says near plumbing.',
  },
  'beetle': {
    id: 'beetle', name: 'Beetle', tier: 4,
    hp: 260, speed: 0.95, size: 0.7, bounty: 65, bites: 1,
    resist: 'swat', weak: 'zap', armor: 7,
    traits: ['anchored'],
    desc: 'A helmet with legs. Does not scoot when flicked, because apparently physics respects confidence.',
  },
  'rat-knight': {
    id: 'rat-knight', name: 'Rat Knight', tier: 4,
    hp: 300, speed: 1.2, size: 0.82, bounty: 75, bites: 2,
    resist: 'swat', weak: 'sonic', armor: 6,
    desc: "Has a bottle-cap shield and tiny mean whiskers. I think it said 'm lady' to the cake before stabbing it.",
  },
  'pillbug': {
    id: 'pillbug', name: 'Pillbug', tier: 3,
    hp: 110, speed: 1.55, size: 0.42, bounty: 28, bites: 1,
    resist: 'swat', weak: 'gas', armor: 3,
    traits: ['rollUp'],
    desc: 'Turns into a marble when scared. Cute until the marble is committing burglary.',
  },
  'earwig': {
    id: 'earwig', name: 'Earwig', tier: 3,
    hp: 78, speed: 2.0, size: 0.36, bounty: 20, bites: 1,
    resist: 'cold', weak: 'sonic',
    traits: ['tunneler'],
    desc: 'Goes under the maze because it did not read the rules. Surfaces near cake like a gross submarine.',
  },
  'tick': {
    id: 'tick', name: 'Tick', tier: 2,
    hp: 45, speed: 2.15, size: 0.18, bounty: 12, bites: 1,
    resist: 'gas', weak: 'heat',
    traits: ['latcher'],
    desc: 'Small dot. Big problem. Hugs towers until they stop helping, which is NOT friendship.',
  },
  'silverfish': {
    id: 'silverfish', name: 'Silverfish', tier: 3,
    hp: 52, speed: 3.85, size: 0.22, bounty: 13, bites: 1,
    resist: 'light', weak: 'spray',
    traits: ['scatter'],
    desc: 'A shiny bookmark that learned parkour. Moves like it stole the answer key and it DID.',
  },
  'mosquito': {
    id: 'mosquito', name: 'Mosquito', tier: 2,
    hp: 38, speed: 2.7, size: 0.26, bounty: 10, bites: 1,
    resist: 'spray', weak: 'zap', flying: true,
    traits: ['healPulse'],
    desc: 'Needle bird. Drinks a little cake and then everybody nearby feels better, which is rude medicine.',
  },
  'wasp-baron': {
    id: 'wasp-baron', name: 'Wasp Baron', tier: 4,
    hp: 190, speed: 2.45, size: 0.5, bounty: 48, bites: 2,
    resist: 'zap', weak: 'cold', flying: true, armor: 1,
    desc: 'Fancy danger with stripes. Owns the sky and maybe a monocle. Stings the cake twice because manners are dead.',
  },
  'hornet': {
    id: 'hornet', name: 'Hornet', tier: 4,
    hp: 160, speed: 2.25, size: 0.46, bounty: 40, bites: 1,
    resist: 'spray', weak: 'sonic', flying: true, armor: 2,
    desc: 'Like a wasp that found the gym and anger coupons. Armor on a flying bug is deeply unfair.',
  },
  'pigeon': {
    id: 'pigeon', name: 'Pigeon', tier: 4,
    hp: 520, speed: 0.9, size: 1.05, bounty: 130, bites: 3,
    resist: 'swat', weak: 'gas', flying: true, armor: 3,
    desc: 'Window cow. Huge. Stares with city eyes. Takes three bites because it has never respected a patio rule.',
  },
  'termite': {
    id: 'termite', name: 'Termite', tier: 3,
    hp: 82, speed: 1.7, size: 0.3, bounty: 21, bites: 0,
    resist: 'gas', weak: 'heat',
    traits: ['clutterEater'], chewDps: 20,
    desc: 'Does not even WANT cake. Wants walls. This is somehow worse because the walls are holding our plan together.',
  },
  'snail-shaman': {
    id: 'snail-shaman', name: 'Snail Shaman', tier: 4,
    hp: 230, speed: 0.55, size: 0.52, bounty: 58, bites: 1,
    resist: 'swat', weak: 'gas', armor: 5,
    traits: ['healPulse'],
    desc: 'Wears a shell and a tiny important hat. Heals the others slowly, which is easy because he does everything slowly.',
  },

  'moadb': {
    id: 'moadb', name: 'M.O.A.D.B.', tier: 5,
    hp: 2200, speed: 0.5, size: 1.35, bounty: 550, bites: 3,
    resist: 'swat', weak: 'spray', boss: true, armor: 2,
    splitInto: { def: 'dust-bunny', count: 4 },
    desc: 'Mother Of All Dust Bunnys. It rolled out from under the couch like winter, but fuzzier and way more bossy.',
  },
  'sir-clogsworth': {
    id: 'sir-clogsworth', name: 'Sir Clogsworth', tier: 5,
    hp: 2800, speed: 0.62, size: 1.25, bounty: 700, bites: 3,
    resist: 'spray', weak: 'zap', boss: true, armor: 3,
    traits: ['submerge'], chewDps: 28,
    desc: 'A drain snake made of soap hair and bad bathtub memories. Dives under, pops up, says blorp with nobility.',
  },
  'bedbug-baron': {
    id: 'bedbug-baron', name: 'The Bedbug Baron', tier: 5,
    hp: 3200, speed: 0.85, size: 1.0, bounty: 800, bites: 3,
    resist: 'swat', weak: 'light', boss: true, armor: 2,
    traits: ['stealth'],
    desc: 'Tiny? NO. Fancy? Yes. Invisible unless lamps catch him doing baron crimes with his little cane.',
  },
  'rat-king': {
    id: 'rat-king', name: 'The Rat King', tier: 5,
    hp: 3800, speed: 0.72, size: 1.3, bounty: 950, bites: 4,
    resist: 'swat', weak: 'sonic', boss: true, armor: 6,
    splitInto: { def: 'rat-knight', count: 3 },
    desc: 'Three rats in a coat pretending to be one tall problem. Honestly the disguise worked for six whole seconds.',
  },
  'grandma-longlegs': {
    id: 'grandma-longlegs', name: 'Grandma Longlegs', tier: 5,
    hp: 4500, speed: 0.68, size: 1.2, bounty: 1125, bites: 4,
    resist: 'cold', weak: 'heat', boss: true, armor: 4,
    traits: ['webber', 'spawner'], spawnDef: 'tick', spawnEvery: 6, spawnCount: 2,
    desc: 'Knits webs and says we look thin. Spawns ticks like candy from a purse. Do not accept the candy.',
  },
  'possum-phantom': {
    id: 'possum-phantom', name: 'The Possum Phantom', tier: 5,
    hp: 5000, speed: 0.7, size: 1.18, bounty: 1250, bites: 4,
    resist: 'cold', weak: 'sonic', boss: true, armor: 4,
    traits: ['playDead'], playDeadTimes: 4,
    desc: 'Dies so many times I wrote THE END four times and had to erase it. Tail twitches when he is doing theater.',
  },
  'trash-panda-don': {
    id: 'trash-panda-don', name: 'The Trash Panda Don', tier: 5,
    hp: 6000, speed: 0.58, size: 1.4, bounty: 1500, bites: 4,
    resist: 'swat', weak: 'light', boss: true, armor: 8,
    traits: ['crumbHeal', 'spawner'], spawnDef: 'possum-jr', spawnEvery: 8, spawnCount: 1,
    desc: 'Garbage lid shield, tiny boss suit, big sandwich energy. Sends possum helpers and eats crumbs like a mob dinner.',
  },
  'the-exterminator': {
    id: 'the-exterminator', name: 'THE EXTERMINATOR', tier: 5,
    hp: 8000, speed: 0.5, size: 1.55, bounty: 2000, bites: 5,
    resist: 'gas', weak: 'zap', boss: true, armor: 10,
    traits: ['towerSmash'], chewDps: 40,
    desc: 'A giant human boot story with a mask and sprayer. Even the bugs looked at us like maybe teamwork is homework now.',
  },
};
