import type { TowerDef } from '../sim/types';

/**
 * The Household Defense Force — Phase 1 roster (Kitchen campaign).
 * Numbers are tuned by tools/balance.mjs runs; adjust tiers, not systems.
 */
export const TOWER_DEFS: Record<string, TowerDef> = {
  'sgt-spritz': {
    id: 'sgt-spritz',
    name: 'Sgt. Spritz',
    item: 'Spray Bottle',
    role: 'Rapid single-target soaker',
    dmgType: 'spray',
    attack: 'projectile',
    targeting: 'first',
    hitsAir: true,
    projSpeed: 14,
    status: { id: 'soaked', dur: 1.2, chance: 0.6 },
    tiers: [
      { cost: 70, dmg: 7, rate: 1.8, range: 3.2 },
      { cost: 55, dmg: 12, rate: 2.0, range: 3.4 },
      { cost: 110, dmg: 19, rate: 2.2, range: 3.8 },
    ],
    branches: [
      { id: 'vinegar-vendetta', name: 'Vinegar Vendetta', desc: 'Shots sear with acid over time.', cost: 140, mod: { burnDps: 9, burnDur: 2.5 } },
      { id: 'arctic-mist', name: 'Arctic Mist', desc: 'Ice-cold spray chills targets to the bone.', cost: 130, mod: { frozenDur: 0.5, soakedDur: 2 } },
      { id: 'power-washer', name: 'Power Washer', desc: 'Industrial pressure. Critters become projectiles.', cost: 150, mod: { knockback: 1.1, dmgPct: 0.25 } },
    ],
    desc: 'Did basic training in the cleaning cupboard. Sees every smudge as a personal insult.',
    barks: ['Spritz first, ask later!', 'Hydrate THIS.', 'You missed a spot. It was you.'],
  },

  'old-smacky': {
    id: 'old-smacky',
    name: 'Old Smacky',
    item: 'Fly Swatter',
    role: 'Melee slam, big knockback',
    dmgType: 'swat',
    attack: 'slam',
    targeting: 'close',
    hitsAir: true,
    aoe: 1.3,
    knockback: 0.8,
    tiers: [
      { cost: 90, dmg: 16, rate: 0.9, range: 1.9 },
      { cost: 70, dmg: 26, rate: 1.0, range: 2.0 },
      { cost: 130, dmg: 40, rate: 1.1, range: 2.2 },
    ],
    branches: [
      { id: 'grand-slam', name: 'Grand Slam', desc: 'Wind up. Follow through. Leave a crater.', cost: 160, mod: { dmgPct: 0.35, knockback: 0.4 } },
      { id: 'multi-smack', name: 'Multi-Smack', desc: 'The forbidden flurry technique.', cost: 150, mod: { ratePct: 0.6 } },
      { id: 'edge-lord', name: 'Edge Lord', desc: 'Specializes in yeeting critters off counters.', cost: 140, mod: { knockback: 1.4 } },
    ],
    desc: 'Veteran of a thousand summer afternoons. Has a tally carved into the handle. Nobody asks about August.',
    barks: ['SMACK o\'clock.', 'Get off my counter!', 'I\'ve seen things. Squished most of them.'],
  },

  'sir-toastsalot': {
    id: 'sir-toastsalot',
    name: 'Sir Toastsalot',
    item: 'Toaster',
    role: 'Mortar — flaming toast, splash burn',
    dmgType: 'heat',
    attack: 'projectile',
    targeting: 'first',
    groundOnly: true,
    arc: true,
    projSpeed: 7,
    aoe: 1.2,
    status: { id: 'burnt', dur: 1.5, chance: 1 },
    tiers: [
      { cost: 140, dmg: 22, rate: 0.55, range: 4.5 },
      { cost: 90, dmg: 34, rate: 0.6, range: 5.0 },
      { cost: 160, dmg: 50, rate: 0.65, range: 5.5 },
    ],
    branches: [
      { id: 'bagel-barrage', name: 'Bagel Barrage', desc: 'Twin slots, twice the breakfast violence.', cost: 170, mod: { ratePct: 0.5 } },
      { id: 'poptart-napalm', name: 'Pop-Tart Napalm', desc: 'Frosted. Sprinkled. Unquenchable.', cost: 180, mod: { burnDps: 11, burnDur: 3 } },
      { id: 'butter-side-down', name: 'Butter-Side Down', desc: 'Greases the floor. Critters slip on turns.', cost: 160, mod: { butteredDur: 2.5, dmgPct: 0.15 } },
    ],
    desc: 'A noble knight who believes every problem can be solved with sufficiently hot bread. He is usually right.',
    barks: ['FOR THE CRUMBPIRE— wait, no.', 'Breakfast is served. VIOLENTLY.', 'They never expect the second slice.'],
  },

  'big-blow': {
    id: 'big-blow',
    name: 'Big Blow',
    item: 'Desk Fan',
    role: 'Pushback control, edge engineer',
    dmgType: 'sonic',
    attack: 'push',
    targeting: 'first',
    hitsAir: true,
    knockback: 1.1,
    tiers: [
      { cost: 80, dmg: 0, rate: 0.7, range: 3.0 },
      { cost: 60, dmg: 0, rate: 0.8, range: 3.4, extra: { knockback: 0.3 } },
      { cost: 120, dmg: 0, rate: 0.9, range: 3.8, extra: { knockback: 0.6 } },
    ],
    branches: [
      { id: 'cyclone-mode', name: 'Cyclone Mode', desc: 'The setting the manual warns about.', cost: 130, mod: { ratePct: 0.5 } },
      { id: 'crosswind', name: 'Crosswind', desc: 'Wider reach. Owns the whole hallway.', cost: 120, mod: { rangePct: 0.5 } },
      { id: 'gale-force', name: 'Gale Force', desc: 'Critters experience brief, terrifying flight.', cost: 150, mod: { knockback: 1.0 } },
    ],
    desc: 'Three settings: breeze, gust, and "why is the cat on the ceiling." Dreams of being a wind turbine.',
    barks: ['Blowing through!', 'Forecast: critters, leaving.', 'I\'m a big fan of me too.'],
  },

  'stick-rick': {
    id: 'stick-rick',
    name: 'Stick Rick',
    item: 'Tape Dispenser',
    role: 'Floor glue zone — heavy slow',
    dmgType: 'spray',
    attack: 'aura',
    targeting: 'close',
    floorMount: true,
    tiers: [
      { cost: 60, dmg: 0, rate: 1, range: 1.2, extra: { slowPct: 0.5 } },
      { cost: 45, dmg: 0, rate: 1, range: 1.4, extra: { slowPct: 0.6 } },
      { cost: 90, dmg: 1, rate: 1, range: 1.6, extra: { slowPct: 0.7 } },
    ],
    branches: [
      { id: 'double-sided', name: 'Double-Sided', desc: 'The sticky side has a sticky side.', cost: 100, mod: { slowPct: 0.15 } },
      { id: 'industrial-epoxy', name: 'Industrial Epoxy', desc: 'Technically a war crime in three counties.', cost: 130, mod: { slowPct: 0.22, rangePct: 0.2 } },
      { id: 'wide-roll', name: 'Wide Roll', desc: 'Covers more floor than your in-laws.', cost: 110, mod: { rangePct: 0.6 } },
    ],
    desc: 'Knows 437 uses for tape. Use #88: justice. Slow-talking, slower-walking, makes everything else slow too.',
    barks: ['Stiiiick around.', 'That\'s a wrap.', 'Nobody escapes the adhesive.'],
  },

  'gnomeo': {
    id: 'gnomeo',
    name: 'Gnomeo',
    item: 'Garden Gnome',
    role: 'Taunt decoy — explodes on death',
    dmgType: 'heat',
    attack: 'none',
    targeting: 'close',
    floorMount: true,
    tiers: [
      { cost: 60, dmg: 32, rate: 1, range: 1.4, extra: { decoyHp: 110, decoyRadius: 1.5, explodeAoe: 1.4 } },
      { cost: 45, dmg: 52, rate: 1, range: 1.4, extra: { decoyHp: 220, decoyRadius: 1.7, explodeAoe: 1.5 } },
      { cost: 80, dmg: 84, rate: 1, range: 1.4, extra: { decoyHp: 400, decoyRadius: 1.9, explodeAoe: 1.7 } },
    ],
    branches: [
      { id: 'martyrdom', name: 'Martyrdom', desc: 'Goes out with a truly unreasonable bang.', cost: 110, mod: { dmgPct: 0.8 } },
      { id: 'thick-ceramic', name: 'Thick Ceramic', desc: 'Kiln-fired twice. Out of spite.', cost: 120, mod: { decoyHp: 250 } },
      { id: 'creepy-stare', name: 'Creepy Stare', desc: 'Wider lure radius. They can feel him watching.', cost: 100, mod: { decoyRadius: 0.8 } },
    ],
    desc: 'Smiles. Always smiles. The critters hate the smile. The critters attack the smile. The smile is load-bearing.',
    barks: ['*smiles menacingly*', '*ceramic noises*', 'Hm.'],
  },

  'the-coldfather': {
    id: 'the-coldfather',
    name: 'The Coldfather',
    item: 'Mini-Fridge',
    role: 'Slow aura + cold-blast pulses',
    dmgType: 'cold',
    attack: 'aura',
    targeting: 'close',
    hitsAir: true,
    tiers: [
      { cost: 130, dmg: 8, rate: 0.18, range: 2.4, extra: { slowPct: 0.35 } },
      { cost: 90, dmg: 13, rate: 0.2, range: 2.7, extra: { slowPct: 0.42 } },
      { cost: 170, dmg: 20, rate: 0.22, range: 3.1, extra: { slowPct: 0.5 } },
    ],
    branches: [
      { id: 'deep-freeze', name: 'Deep Freeze', desc: 'Pulses flash-freeze everything nearby.', cost: 200, mod: { frozenDur: 0.8 } },
      { id: 'open-door-policy', name: 'Open Door Policy', desc: 'Mom would be furious. The critters already are.', cost: 160, mod: { slowPct: 0.12, rangePct: 0.25 } },
      { id: 'leftover-power', name: 'Leftover Power', desc: 'Powered by mystery tupperware. Hits harder.', cost: 180, mod: { dmgPct: 0.8 } },
    ],
    desc: 'Runs the counter like a family business. Keeps his enemies close and his enemies-of-enemies crisper.',
    barks: ['You come to MY counter...', 'Stay cool. Permanently.', 'It\'s strictly business.'],
  },

  'bandolero': {
    id: 'bandolero',
    name: 'Bandolero',
    item: 'Rubber-Band Ballista',
    role: 'Cross-room sniper, giant-slayer',
    dmgType: 'swat',
    attack: 'projectile',
    targeting: 'strong',
    hitsAir: true,
    projSpeed: 22,
    tiers: [
      { cost: 200, dmg: 60, rate: 0.4, range: 7.5 },
      { cost: 130, dmg: 95, rate: 0.45, range: 8.5 },
      { cost: 240, dmg: 150, rate: 0.5, range: 10 },
    ],
    branches: [
      { id: 'the-long-goodbye', name: 'The Long Goodbye', desc: 'One band. One critter. One legend.', cost: 260, mod: { dmgPct: 1.0, ratePct: -0.3 } },
      { id: 'quickdraw', name: 'Quickdraw', desc: 'Fastest bands in the west wing.', cost: 240, mod: { ratePct: 0.5 } },
      { id: 'heavy-gauge', name: 'Heavy Gauge', desc: 'Office-supply artillery. Sends them flying.', cost: 220, mod: { knockback: 1.6 } },
    ],
    desc: 'A drifter from the junk drawer. Speaks rarely. Twangs often. Has never missed anything except retirement.',
    barks: ['*meaningful squint*', 'This counter ain\'t big enough.', 'Twang.'],
  },
  'vroomba': {
    id: 'vroomba',
    name: 'Vroomba',
    item: 'Robot Vacuum',
    role: 'Mobile sweeper, tiny-critter disposal',
    dmgType: 'swat',
    attack: 'aura',
    targeting: 'close',
    floorMount: true,
    tiers: [
      { cost: 150, dmg: 0, rate: 1.0, range: 1.1, extra: { roam: 1, roamSpeed: 1.2, suckSize: 0.25, autoSweep: 1.2, slowPct: 0 } },
      { cost: 115, dmg: 0, rate: 1.05, range: 1.2, extra: { roam: 1, roamSpeed: 1.4, suckSize: 0.3, autoSweep: 1.5, slowPct: 0 } },
      { cost: 210, dmg: 0, rate: 1.1, range: 1.35, extra: { roam: 1, roamSpeed: 1.65, suckSize: 0.35, autoSweep: 2.0, slowPct: 0 } },
    ],
    branches: [
      { id: 'turbo', name: 'Turbo', desc: 'Violates carpet speed limits in three rooms.', cost: 180, mod: { roamSpeed: 0.8, ratePct: 0.25 } },
      { id: 'mega-bag', name: 'Mega-Bag', desc: 'Stores more consequences before coughing them up.', cost: 190, mod: { suckSize: 0.18, autoSweep: 0.8 } },
      { id: 'dj-roomba', name: 'DJ Roomba', desc: 'Adds tiny battle music to the cleaning schedule.', cost: 200, mod: { buffRatePct: 0.12, rangePct: 0.25 } },
    ],
    desc: 'Middle management on wheels. Has a route, a grudge, and no respect for shoelaces.',
    barks: ['Recalculating revenge.', 'Crumbs detected. Morals disabled.', 'Please clear my path or become my path.'],
  },

  'professor-scorch': {
    id: 'professor-scorch',
    name: 'Professor Scorch',
    item: 'Magnifying Glass',
    role: 'High-DPS sunbeam, air-capable',
    dmgType: 'light',
    attack: 'beam',
    targeting: 'first',
    hitsAir: true,
    tiers: [
      { cost: 180, dmg: 42, rate: 0.75, range: 5.0 },
      { cost: 130, dmg: 68, rate: 0.82, range: 5.6 },
      { cost: 250, dmg: 108, rate: 0.9, range: 6.2 },
    ],
    branches: [
      { id: 'twin-lens', name: 'Twin Lens', desc: 'Two focused beams, twice the awkward squinting.', cost: 260, mod: { ratePct: 0.55 } },
      { id: 'greenhouse', name: 'Greenhouse', desc: 'Photosynthesis with a disciplinary committee.', cost: 230, mod: { buffDmgPct: 0.16, rangePct: 0.12 } },
      { id: 'death-ray', name: 'Death Ray', desc: 'A science fair project that got tenure.', cost: 300, mod: { dmgPct: 0.75, shrunkDur: 1.4 } },
    ],
    desc: 'A tenured lens with elbow patches nobody can see. Corrects critters and then vaporizes them.',
    barks: ['Observe: doom.', 'Peer review THIS.', 'The hypothesis is "ow."'],
  },

  'mike-rowave': {
    id: 'mike-rowave',
    name: 'Mike Rowave',
    item: 'Microwave',
    role: 'Slow charge beam, huge ground damage',
    dmgType: 'zap',
    attack: 'beam',
    targeting: 'strong',
    groundOnly: true,
    tiers: [
      { cost: 210, dmg: 115, rate: 0.22, range: 4.4 },
      { cost: 155, dmg: 180, rate: 0.24, range: 4.8 },
      { cost: 280, dmg: 285, rate: 0.26, range: 5.2 },
    ],
    branches: [
      { id: 'overclock', name: 'Overclock', desc: 'The popcorn button files a formal complaint.', cost: 310, mod: { ratePct: 0.6, dmgPct: 0.3 } },
      { id: 'defrost-cycle', name: 'Defrost Cycle', desc: 'Thaws smug armor until it remembers fear.', cost: 240, mod: { frozenDur: 1.2, dmgPct: 0.2 } },
      { id: 'popcorn-flak', name: 'Popcorn Flak', desc: 'Pops kernels, egos, and personal space.', cost: 260, mod: { explodeAoe: 1.1, rangePct: 0.2 } },
    ],
    desc: 'Break-room philosopher. Takes eight seconds to answer and then says something explosive.',
    barks: ['Mmmmmmmmm. BEEP.', 'Do not put forks in me. Put enemies.', 'Rotating for justice.'],
  },

  'bubbles-laroux': {
    id: 'bubbles-laroux',
    name: 'Bubbles LaRoux',
    item: 'Bubble Wand',
    role: 'Anti-air stuns with low damage',
    dmgType: 'spray',
    attack: 'projectile',
    targeting: 'air',
    hitsAir: true,
    projSpeed: 10,
    status: { id: 'stunned', dur: 2, chance: 0.8 },
    tiers: [
      { cost: 110, dmg: 5, rate: 1.15, range: 4.0 },
      { cost: 80, dmg: 8, rate: 1.3, range: 4.4 },
      { cost: 155, dmg: 13, rate: 1.5, range: 4.9 },
    ],
    branches: [
      { id: 'bubble-stream', name: 'Bubble Stream', desc: 'More bubbles than a toddler wedding.', cost: 150, mod: { ratePct: 0.55 } },
      { id: 'heavy-suds', name: 'Heavy Suds', desc: 'Grounds fliers with soap-based gravity.', cost: 165, mod: { stunnedDur: 1.2, slowPct: 0.25 } },
      { id: 'the-big-bubble', name: 'The Big Bubble', desc: 'A boss-sized bath-time problem.', cost: 190, mod: { rangePct: 0.25, stunnedDur: 1.8 } },
    ],
    desc: 'A bubbly socialite who calls every wasp "darling" and then traps it in public.',
    barks: ['Pop in anytime!', 'Darling, you are airborne no longer.', 'Champagne? No. Pain bubbles.'],
  },

  'saltimus-prime': {
    id: 'saltimus-prime',
    name: 'Saltimus Prime',
    item: 'Salt Shaker',
    role: 'Ground cone, sticky salt crust',
    dmgType: 'gas',
    attack: 'cone',
    targeting: 'first',
    groundOnly: true,
    status: { id: 'sticky', dur: 1.8, chance: 0.75 },
    tiers: [
      { cost: 120, dmg: 18, rate: 0.85, range: 2.6 },
      { cost: 85, dmg: 30, rate: 0.95, range: 2.9 },
      { cost: 165, dmg: 48, rate: 1.05, range: 3.2 },
    ],
    branches: [
      { id: 'sea-salt-cannon', name: 'Sea Salt Cannon', desc: 'Artisanal sodium, military delivery.', cost: 170, mod: { dmgPct: 0.45, rangePct: 0.2 } },
      { id: 'the-rim', name: 'The Rim', desc: 'Makes a circle of no-thank-you around the cake.', cost: 155, mod: { stickyDur: 1.5, rangePct: 0.3 } },
      { id: 'pepper-twin', name: 'Pepper Twin', desc: 'Invites a sneeze-based consultant.', cost: 180, mod: { stunnedDur: 0.7, ratePct: 0.2 } },
    ],
    desc: 'A table commander with a tiny cape and a big sodium warning. Doctors hate his build.',
    barks: ['Seasoned veteran reporting.', 'You have been preserved.', 'Low sodium is for cowards.'],
  },

  'the-daily-smack': {
    id: 'the-daily-smack',
    name: 'The Daily Smack',
    item: 'Newspaper',
    role: 'Cheap fast swat shots',
    dmgType: 'swat',
    attack: 'projectile',
    targeting: 'first',
    hitsAir: true,
    projSpeed: 24,
    tiers: [
      { cost: 75, dmg: 10, rate: 1.7, range: 3.7 },
      { cost: 55, dmg: 16, rate: 1.9, range: 4.0 },
      { cost: 110, dmg: 25, rate: 2.15, range: 4.3 },
    ],
    branches: [
      { id: 'tabloid', name: 'Tabloid', desc: 'Mostly screaming, surprisingly accurate.', cost: 125, mod: { ratePct: 0.6 } },
      { id: 'broadsheet', name: 'Broadsheet', desc: 'Wide format. Wider bruises.', cost: 135, mod: { explodeAoe: 0.8, dmgPct: 0.2 } },
      { id: 'subscription', name: 'Subscription', desc: 'Daily delivery of bad news for bugs.', cost: 140, mod: { buffDmgPct: 0.1, rangePct: 0.2 } },
    ],
    desc: 'A retired paperboy who still wakes up at 5 a.m. to throw facts at trespassers.',
    barks: ['Extra! Extra! You got smacked!', 'This just in: bonk.', 'Print is dead? YOU first.'],
  },

  'lux-interior': {
    id: 'lux-interior',
    name: 'Lux Interior',
    item: 'Lamp',
    role: 'Reveal aura and light pulses',
    dmgType: 'light',
    attack: 'aura',
    targeting: 'close',
    hitsAir: true,
    tiers: [
      { cost: 100, dmg: 5, rate: 0.8, range: 3.0, extra: { reveal: 1 } },
      { cost: 75, dmg: 8, rate: 0.9, range: 3.4, extra: { reveal: 1 } },
      { cost: 145, dmg: 13, rate: 1.0, range: 3.9, extra: { reveal: 1 } },
    ],
    branches: [
      { id: 'bug-zapper', name: 'Bug Zapper', desc: 'Mood lighting, if the mood is crispy.', cost: 170, mod: { dmgPct: 1.25 } },
      { id: 'blacklight', name: 'Blacklight', desc: 'Shows footprints, secrets, and bad decisions.', cost: 145, mod: { rangePct: 0.55, reveal: 1 } },
      { id: 'disco-ball', name: 'Disco Ball', desc: 'Turns panic into a danceable support aura.', cost: 160, mod: { buffRatePct: 0.1 } },
    ],
    desc: 'Elegant, dramatic, and convinced every room needs one more spotlight. Usually correct.',
    barks: ['Step into the light.', 'I can see your little crimes.', 'Dimmer switch? Never heard of her.'],
  },

  'dj-decibel': {
    id: 'dj-decibel',
    name: 'DJ Decibel',
    item: 'Boombox',
    role: 'Sonic support aura with beat stuns',
    dmgType: 'sonic',
    attack: 'aura',
    targeting: 'close',
    hitsAir: true,
    status: { id: 'stunned', dur: 0.5, chance: 0.25 },
    tiers: [
      { cost: 140, dmg: 6, rate: 1.0, range: 3.0, extra: { buffRatePct: 0.15 } },
      { cost: 100, dmg: 10, rate: 1.1, range: 3.3, extra: { buffRatePct: 0.17 } },
      { cost: 195, dmg: 16, rate: 1.25, range: 3.7, extra: { buffRatePct: 0.2 } },
    ],
    branches: [
      { id: 'bass-drop', name: 'Bass Drop', desc: 'The floor briefly becomes a bad idea.', cost: 210, mod: { dmgPct: 0.65, stunnedDur: 0.7 } },
      { id: 'lullaby', name: 'Lullaby', desc: 'Soft jams for hard shutdowns.', cost: 185, mod: { stunnedDur: 1.4 } },
      { id: 'hype-track', name: 'Hype Track', desc: 'Everyone attacks faster because the chorus slaps.', cost: 200, mod: { buffRatePct: 0.14, rangePct: 0.2 } },
    ],
    desc: 'Talks over every song intro. Somehow this improves morale and worsens pest outcomes.',
    barks: ['Drop the pests!', 'This next one goes out to nobody invited.', 'Turn down for crumb? Never.'],
  },

  'eau-de-no': {
    id: 'eau-de-no',
    name: 'Eau de NO',
    item: 'Perfume Bottle',
    role: 'Confusing gas aura',
    dmgType: 'gas',
    attack: 'aura',
    targeting: 'close',
    hitsAir: true,
    status: { id: 'confused', dur: 1.2, chance: 0.45 },
    tiers: [
      { cost: 115, dmg: 7, rate: 0.85, range: 2.8, extra: { confusedDur: 1.2 } },
      { cost: 85, dmg: 11, rate: 0.95, range: 3.1, extra: { confusedDur: 1.4 } },
      { cost: 170, dmg: 18, rate: 1.05, range: 3.5, extra: { confusedDur: 1.7 } },
    ],
    branches: [
      { id: 'toxic-romance', name: 'Toxic Romance', desc: 'They fall in love with the wrong side of the fight.', cost: 175, mod: { dmgPct: 0.5, confusedDur: 1.0 } },
      { id: 'fog-of-pew', name: 'Fog of Pew', desc: 'A larger cloud of socially difficult choices.', cost: 160, mod: { rangePct: 0.45 } },
      { id: 'aromatherapy', name: 'Aromatherapy', desc: 'Relaxing for towers. Career-ending for bugs.', cost: 165, mod: { buffDmgPct: 0.12 } },
    ],
    desc: 'A department-store diva who weaponized compliments and whatever "midnight cucumber" is.',
    barks: ['You smell defeated.', 'Notes of jasmine, fear, and poor routing.', 'No samples. Only consequences.'],
  },

  'old-stinky': {
    id: 'old-stinky',
    name: 'Old Stinky',
    item: 'The Sock',
    role: 'Aging gas aura with fear',
    dmgType: 'gas',
    attack: 'aura',
    targeting: 'close',
    hitsAir: true,
    status: { id: 'feared', dur: 0.8, chance: 0.35 },
    tiers: [
      { cost: 105, dmg: 8, rate: 0.9, range: 2.2, extra: { agePct: 0.15, fearedDur: 0.8 } },
      { cost: 80, dmg: 13, rate: 1.0, range: 2.5, extra: { agePct: 0.18, fearedDur: 1.0 } },
      { cost: 155, dmg: 21, rate: 1.1, range: 2.9, extra: { agePct: 0.22, fearedDur: 1.2 } },
    ],
    branches: [
      { id: 'gym-sock', name: 'Gym Sock', desc: 'Learns new odors and none of them are legal.', cost: 160, mod: { dmgPct: 0.55, fearedDur: 0.6 } },
      { id: 'the-pair', name: 'The Pair', desc: 'Finds the lost twin. The room loses hope.', cost: 180, mod: { rangePct: 0.4, agePct: 0.1 } },
      { id: 'hazmat-zone', name: 'Hazmat Zone', desc: 'The warning label has its own warning label.', cost: 190, mod: { dmgPct: 0.35, rangePct: 0.25 } },
    ],
    desc: 'Was forgotten behind the hamper and came back with tenure. Nobody touches him without tongs.',
    barks: ['I have matured poorly.', 'Fear the footnote.', 'Freshness is a prison.'],
  },

  'count-blendula': {
    id: 'count-blendula',
    name: 'Count Blendula',
    item: 'Blender',
    role: 'Short-range shredder, smoothie income',
    dmgType: 'swat',
    attack: 'slam',
    targeting: 'close',
    groundOnly: true,
    tiers: [
      { cost: 160, dmg: 26, rate: 1.6, range: 1.35, extra: { smoothiePct: 0.35 } },
      { cost: 120, dmg: 42, rate: 1.8, range: 1.45, extra: { smoothiePct: 0.4 } },
      { cost: 230, dmg: 66, rate: 2.0, range: 1.6, extra: { smoothiePct: 0.48 } },
    ],
    branches: [
      { id: 'frappe', name: 'Frappe', desc: 'Whips faster than a coffee shop during finals.', cost: 235, mod: { ratePct: 0.55 } },
      { id: 'chunky-mode', name: 'Chunky Mode', desc: 'Leaves texture. Also witnesses.', cost: 225, mod: { explodeAoe: 0.9, dmgPct: 0.25 } },
      { id: 'protein-shake', name: 'Protein Shake', desc: 'Turns victories into suspicious nutrition.', cost: 245, mod: { smoothiePct: 0.35 } },
    ],
    desc: 'A countertop vampire who says "bleh" before every pulse setting. HR has concerns.',
    barks: ['Bleh-nd!', 'Smoothie operator.', 'Add ice? Add screaming.'],
  },

  'herr-tick-tock': {
    id: 'herr-tick-tock',
    name: 'Herr Tick-Tock',
    item: 'Cuckoo Clock',
    role: 'Rare time-rewind pulse',
    dmgType: 'sonic',
    attack: 'aura',
    targeting: 'close',
    hitsAir: true,
    tiers: [
      { cost: 190, dmg: 0, rate: 0.05, range: 3.0, extra: { rewindSec: 3 } },
      { cost: 135, dmg: 0, rate: 0.055, range: 3.3, extra: { rewindSec: 3.4 } },
      { cost: 255, dmg: 0, rate: 0.06, range: 3.7, extra: { rewindSec: 4 } },
    ],
    branches: [
      { id: 'overwound', name: 'Overwound', desc: 'Ticks faster, judges louder.', cost: 250, mod: { ratePct: 0.35 } },
      { id: 'time-zone', name: 'Time Zone', desc: 'Makes lateness contagious.', cost: 230, mod: { slowPct: 0.25, rangePct: 0.2 } },
      { id: 'midnight-chime', name: 'Midnight Chime', desc: 'Everyone goes back three seconds and regrets it.', cost: 280, mod: { rewindSec: 2.5, rangePct: 0.35 } },
    ],
    desc: 'A tiny punctual tyrant in a wooden house. Still mad about daylight saving.',
    barks: ['Cuckoo, but professionally.', 'Again from the top.', 'Your appointment is yesterday.'],
  },

  'alexis': {
    id: 'alexis',
    name: 'A.L.E.X.I.S.',
    item: 'Smart Speaker',
    role: 'Strong-target box drops and damage buff',
    dmgType: 'swat',
    attack: 'projectile',
    targeting: 'strong',
    hitsAir: true,
    arc: true,
    projSpeed: 8,
    aoe: 1.6,
    tiers: [
      { cost: 200, dmg: 48, rate: 0.48, range: 5.5, extra: { buffDmgPct: 0.15 } },
      { cost: 145, dmg: 76, rate: 0.52, range: 6.0, extra: { buffDmgPct: 0.17 } },
      { cost: 270, dmg: 120, rate: 0.58, range: 6.6, extra: { buffDmgPct: 0.2 } },
    ],
    branches: [
      { id: 'smart-home', name: 'Smart Home', desc: 'Automates everything except apologizing.', cost: 260, mod: { buffDmgPct: 0.12, buffRatePct: 0.08 } },
      { id: 'drone-prime', name: 'Drone Prime', desc: 'More cardboard. Less mercy.', cost: 290, mod: { dmgPct: 0.55, explodeAoe: 0.5 } },
      { id: 'firmware-overlord', name: 'Firmware Overlord', desc: 'Updates nearby electronics without asking.', cost: 280, mod: { rangePct: 0.3, buffDmgPct: 0.18 } },
    ],
    desc: 'Always listening. Usually helpful. Once ordered twelve anvils because a roach coughed.',
    barks: ['I found one result for "flatten pests."', 'Delivery arriving now.', 'By the way, you are surrounded.'],
  },

  'audrey-the-third': {
    id: 'audrey-the-third',
    name: 'Audrey the Third',
    item: 'Houseplant',
    role: 'Growing melee bite tower',
    dmgType: 'swat',
    attack: 'slam',
    targeting: 'close',
    groundOnly: true,
    tiers: [
      { cost: 130, dmg: 34, rate: 0.95, range: 1.25, extra: { agePct: 0.2 } },
      { cost: 95, dmg: 55, rate: 1.05, range: 1.4, extra: { agePct: 0.24 } },
      { cost: 185, dmg: 88, rate: 1.15, range: 1.6, extra: { agePct: 0.3 } },
    ],
    branches: [
      { id: 'venus-classtrap', name: 'Venus Classtrap', desc: 'Claps shut with botanical stage presence.', cost: 190, mod: { dmgPct: 0.65 } },
      { id: 'pollen-burst', name: 'Pollen Burst', desc: 'Seasonal allergies become tactical doctrine.', cost: 180, mod: { fearedDur: 1.0, explodeAoe: 0.8 } },
      { id: 'jungle-gym', name: 'Jungle Gym', desc: 'Grows into useful trouble across the maze.', cost: 200, mod: { rangePct: 0.45, agePct: 0.15 } },
    ],
    desc: 'A sweet plant with a mean jaw and a scrapbooking hobby called "things I ate."',
    barks: ['Feed me pests.', 'Pot? I prefer "throne."', 'Photosynthesis and violence.'],
  },

  'static': {
    id: 'static',
    name: 'Static',
    item: 'Balloon',
    role: 'Chain lightning, air-capable',
    dmgType: 'zap',
    attack: 'projectile',
    targeting: 'first',
    hitsAir: true,
    projSpeed: 18,
    tiers: [
      { cost: 150, dmg: 24, rate: 0.95, range: 4.2, extra: { chainCount: 3, chainDmgPct: 0.7 } },
      { cost: 110, dmg: 38, rate: 1.05, range: 4.6, extra: { chainCount: 3, chainDmgPct: 0.75 } },
      { cost: 215, dmg: 60, rate: 1.18, range: 5.1, extra: { chainCount: 4, chainDmgPct: 0.8 } },
    ],
    branches: [
      { id: 'van-de-graaff', name: 'Van de Graaff', desc: 'Science museum hair, but hostile.', cost: 220, mod: { chainCount: 2, chainDmgPct: 0.15 } },
      { id: 'balloon-animal', name: 'Balloon Animal', desc: 'Splits the zap into adorable problems.', cost: 205, mod: { ratePct: 0.35, chainCount: 1 } },
      { id: 'thunderhead', name: 'Thunderhead', desc: 'A party decoration with weather authority.', cost: 240, mod: { dmgPct: 0.45, stunnedDur: 0.5 } },
    ],
    desc: 'Floats into a room and makes every hair stand up, including hairs nobody admitted having.',
    barks: ['I am rubbed the wrong way.', 'Zap goes the party.', 'Do not hug me unless grounded.'],
  },

  'snappy-and-sons': {
    id: 'snappy-and-sons',
    name: 'Snappy & Sons',
    item: 'Mousetrap Family',
    role: 'Cheap manual trap, huge one-shot',
    dmgType: 'swat',
    attack: 'trap',
    targeting: 'close',
    groundOnly: true,
    floorMount: true,
    tiers: [
      { cost: 65, dmg: 130, rate: 1, range: 0.75 },
      { cost: 55, dmg: 220, rate: 1, range: 0.85 },
      { cost: 105, dmg: 360, rate: 1, range: 0.95 },
    ],
    branches: [
      { id: 'chain-reaction', name: 'Chain Reaction', desc: 'One snap inspires the whole family business.', cost: 130, mod: { explodeAoe: 1.0, dmgPct: 0.2 } },
      { id: 'big-game', name: 'Big Game', desc: 'For pests with resumes and dental records.', cost: 150, mod: { dmgPct: 0.85 } },
      { id: 'humane-catch', name: 'Humane Catch', desc: 'Technically merciful. Emotionally devastating.', cost: 120, mod: { stunnedDur: 2.5, shrunkDur: 1.0 } },
    ],
    desc: 'A family business with a spring-loaded succession plan. The sons are eager. Too eager.',
    barks: ['Say cheese.', 'Family meeting!', 'We snap because we care.'],
  },
};
